### ISSUE TITLE
Sudo Required for install and use

### ISSUE THREAD

**Issue by Porco-Rosso** [ajrosen/icalPal#21]
Hello again, I have found that in order to update or execute iCalPal I now require sudo rights. This wasn't the case originally. I assume it is due to some recent changes?

When executing iCalpal without Sudo I get the following:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- core_ext/string (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-plist-0.5.0/lib/nokogiri-plist.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/lib/reminder.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/lib/icalPal.rb:6:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/lib/icalPal.rb:6:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/bin/icalPal:12:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/bin/icalPal:12:in `<top (required)>'
	from /usr/local/bin/icalPal:23:in `load'
	from /usr/local/bin/icalPal:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- core_ext/string (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-plist-0.5.0/lib/nokogiri-plist.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/lib/reminder.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/lib/icalPal.rb:6:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/lib/icalPal.rb:6:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/bin/icalPal:12:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/icalPal-2.0.0/bin/icalPal:12:in `<top (required)>'
	from /usr/local/bin/icalPal:23:in `load'
	from /usr/local/bin/icalPal:23:in `<main>'
```

**Comment by ajrosen** [comment]
Yes, 2.0.0 has a new dependency (nokogiri-plist) to implement the tasks commands.  Your error shows it didn't get installed :(.  I think your options are:

`gem install --user-install icalPal` to install it in your home directory instead of system-wide.

`gem install nokogiri-plist` to install the dependency (might need sudo or --user-install as well)

or

```
brew tap ajrosen/icalpal
brew install icalpal
```

if you use Homebrew.

In the meantime I've added the `--user-install` option to the README, and plan to catch dependency errors to print better error messages.

Thanks!
